

- name: Download and install haproxy
  yum: name={{ item }} state=present
  with_items:
   - libsemanage-python
   - libselinux-python
   - haproxy
   - dnsmasq

- name: Render template
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg mode=0640 owner=root group=root
  notify:
    - restart haproxy

# TBD use router image or:

# - name: ipv4 router
# set echo 1 > /proc/sys/net/ipv4/ip_forward
#


# - name: iptables disable

